// alu_insys.v

// Generated using ACDS version 22.1 915

`timescale 1 ps / 1 ps
module alu_insys (
		input  wire [68:0] probe,  //  probes.probe
		output wire [32:0] source  // sources.source
	);

	altsource_probe_top #(
		.sld_auto_instance_index ("YES"),
		.sld_instance_index      (0),
		.instance_id             ("NONE"),
		.probe_width             (69),
		.source_width            (33),
		.source_initial_value    ("0"),
		.enable_metastability    ("NO")
	) in_system_sources_probes_0 (
		.source     (source), // sources.source
		.probe      (probe),  //  probes.probe
		.source_ena (1'b1)    // (terminated)
	);

endmodule
